const keys = { 
    API_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
    NFT_STORAGE_URL: process.env.NEXT_PUBLIC_NFT_STORAGE_URL,
    NFT_STORAGE_KEY: process.env.NEXT_PUBLIC_API_NFT_STORAGE_KEY,
    MINT_CONTRACT: process.env.NEXT_PUBLIC_MINT_CONTRACT,
    FETCH_CONTRACT: process.env.NEXT_PUBLIC_FETCH_CONTRACT
}
export default keys;